import pathlib, re, subprocess, sys
gen_path = pathlib.Path(r"C:\Users\Fahad\Desktop\rfp\rfp platform\generate_presentations.py")
text = gen_path.read_text(encoding="utf-8", errors="replace")
new_pres = r'''PRES = """<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} — DoSLR Presentation</title><style>:root{{--paper:#EEF1F5;--panel:#FFF;--ink:#13213B;--line:#CBD4E1;--sans:ui-sans-serif,system-ui,sans-serif;--mono:ui-monospace,Consolas,monospace}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans)}}.back-bar{{padding:14px 22px}}.back{{color:var(--ink);text-decoration:none;font-family:var(--mono);font-size:12px;opacity:.75}}.back:hover{{opacity:1}}main{{max-width:1100px;margin:0 auto;padding:0 22px 22px}}.canvas{{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:18px;min-height:320px;display:flex;justify-content:center;box-shadow:0 8px 24px rgba(19,33,59,.06)}}.canvas .mermaid{{width:100%;display:flex;justify-content:center}}.canvas svg{{max-width:100%;height:auto}}</style></head><body><div class="back-bar"><a class="back" href="../index.html">← All presentations</a></div><main><div class="canvas"><div class="mermaid" id="diagram"></div></div></main><script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.3/mermaid.min.js"></script><script>const STEPS={steps_json};let stepIndex=0,renderSeq=0;mermaid.initialize({{startOnLoad:false,securityLevel:"loose",theme:"base",fontFamily:"ui-sans-serif,system-ui,sans-serif",themeVariables:{{background:"transparent",primaryColor:"#E9EEF6",primaryBorderColor:"#13213B",primaryTextColor:"#13213B",lineColor:"#7C8BA6",secondaryColor:"#F4E6DC",tertiaryColor:"#FFFFFF",mainBkg:"#E9EEF6",nodeBorder:"#33425E",clusterBkg:"#F7F9FC",clusterBorder:"#C2CCDC",titleColor:"#13213B",edgeLabelBackground:"#EEF1F5",actorBkg:"#E9EEF6",actorBorder:"#33425E",actorTextColor:"#13213B",signalColor:"#46546F",signalTextColor:"#13213B",labelBoxBkgColor:"#F4E6DC",labelBoxBorderColor:"#D9542B",noteBkgColor:"#F4E6DC",noteBorderColor:"#D9542B",noteTextColor:"#13213B",attributeBackgroundColorPeach:"#F4E6DC",attributeBackgroundColorOdd:"#FFFFFF",attributeBackgroundColorEven:"#F2F5F9"}},flowchart:{{curve:"basis",useMaxWidth:true,htmlLabels:true,padding:14}},er:{{useMaxWidth:true}},sequence:{{useMaxWidth:true,actorMargin:42,boxMargin:8}}}});const diagramEl=document.getElementById("diagram");async function renderStep(){{const seq=++renderSeq;const step=STEPS[stepIndex];diagramEl.removeAttribute("data-processed");diagramEl.textContent=step.mermaid;try{{await mermaid.run({{nodes:[diagramEl]}})}}catch(err){{if(seq===renderSeq)diagramEl.innerHTML=`<pre style="color:#D9542B">${{err.message}}</pre>`}}}}document.addEventListener("keydown",e=>{{if(e.key==="ArrowLeft"&&stepIndex>0){{stepIndex--;renderStep()}}if(e.key==="ArrowRight"&&stepIndex<STEPS.length-1){{stepIndex++;renderStep()}}}});renderStep();</script></body></html>"""'''
new_format = 'out.write_text(PRES.format(title=html.escape(d["title"]), steps_json=json.dumps(steps, ensure_ascii=False)), encoding="utf-8")'
text2, n = re.subn(r'PRES = """.*?"""', new_pres, text, count=1, flags=re.DOTALL)
if n != 1: raise SystemExit(f"PRES replace failed: {n}")
text2, n2 = re.subn(r'out\.write_text\(PRES\.format\([^)]+\), encoding="utf-8"\)', new_format, text2, count=1)
if n2 != 1: raise SystemExit(f"format replace failed: {n2}")
gen_path.write_text(text2, encoding="utf-8")
print("patched")
subprocess.run([sys.executable, str(gen_path)], check=True)
